import type { Hotel, Car } from '@/types/booking';

export const hotels: Hotel[] = [
    {
        id: '1',
        name: 'Grand Hotel Amsterdam',
        location: 'Amsterdam, Netherlands',
        country: 'NL',
        rating: 4.7,
        reviewCount: 2341,
        pricePerNight: 189,
        image: 'https://loremflickr.com/1200/800/hotel,amsterdam?lock=101',
        description:
            'A stunning 5-star hotel located in the heart of Amsterdam, overlooking the famous canals. Enjoy world-class dining, a luxurious spa, and easy access to museums and cultural attractions.',
        amenities: [
            'Free WiFi',
            'Spa',
            'Restaurant',
            'Bar',
            'Room Service',
            'Fitness Center',
            'Parking',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Standard Double',
                pricePerNight: 189,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r2',
                name: 'Deluxe Suite',
                pricePerNight: 329,
                maxGuests: 2,
                bedType: 'King',
            },
            {
                id: 'r3',
                name: 'Family Room',
                pricePerNight: 269,
                maxGuests: 4,
                bedType: '2 Doubles',
            },
        ],
    },
    {
        id: '2',
        name: 'Hotel Bella Vista',
        location: 'Rome, Italy',
        country: 'IT',
        rating: 4.5,
        reviewCount: 1876,
        pricePerNight: 155,
        image: 'https://loremflickr.com/1200/800/hotel,rome?lock=102',
        description:
            'Charming boutique hotel near the Colosseum with panoramic rooftop terrace. Experience authentic Italian hospitality with modern comforts and breathtaking views of the Eternal City.',
        amenities: [
            'Free WiFi',
            'Rooftop Terrace',
            'Restaurant',
            'Air Conditioning',
            'Concierge',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Classic Room',
                pricePerNight: 155,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r2',
                name: 'Superior Room',
                pricePerNight: 215,
                maxGuests: 2,
                bedType: 'King',
            },
            {
                id: 'r3',
                name: 'Junior Suite',
                pricePerNight: 295,
                maxGuests: 3,
                bedType: 'King',
            },
        ],
    },
    {
        id: '3',
        name: 'Le Parisien Hotel',
        location: 'Paris, France',
        country: 'FR',
        rating: 4.8,
        reviewCount: 3102,
        pricePerNight: 245,
        image: 'https://loremflickr.com/1200/800/hotel,paris?lock=103',
        description:
            'Elegant Parisian hotel steps from the Champs-Élysées. Featuring Art Deco interiors, a Michelin-starred restaurant, and the finest French hospitality in the City of Light.',
        amenities: [
            'Free WiFi',
            'Restaurant',
            'Bar',
            'Spa',
            'Valet Parking',
            'Fitness Center',
            'Business Center',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Chambre Classique',
                pricePerNight: 245,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r2',
                name: 'Chambre Supérieure',
                pricePerNight: 345,
                maxGuests: 2,
                bedType: 'King',
            },
            {
                id: 'r3',
                name: 'Suite Parisienne',
                pricePerNight: 520,
                maxGuests: 3,
                bedType: 'King',
            },
        ],
    },
    {
        id: '4',
        name: 'Barcelona Beach Resort',
        location: 'Barcelona, Spain',
        country: 'ES',
        rating: 4.4,
        reviewCount: 1543,
        pricePerNight: 175,
        image: 'https://loremflickr.com/1200/800/beach,resort?lock=104',
        description:
            'Modern beachfront resort on the Mediterranean coast. Perfect for combining business and leisure with stunning sea views, outdoor pool, and direct beach access.',
        amenities: [
            'Free WiFi',
            'Pool',
            'Beach Access',
            'Restaurant',
            'Bar',
            'Spa',
            'Kids Club',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Sea View Room',
                pricePerNight: 175,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r2',
                name: 'Premium Suite',
                pricePerNight: 310,
                maxGuests: 2,
                bedType: 'King',
            },
            {
                id: 'r3',
                name: 'Family Suite',
                pricePerNight: 385,
                maxGuests: 5,
                bedType: '2 Doubles + Single',
            },
        ],
    },
    {
        id: '5',
        name: 'Hotel Zur Altstadt',
        location: 'Vienna, Austria',
        country: 'AT',
        rating: 4.6,
        reviewCount: 987,
        pricePerNight: 165,
        image: 'https://loremflickr.com/1200/800/boutique,hotel?lock=105',
        description:
            "Historic hotel in the heart of Vienna's old town, steps from St. Stephen's Cathedral. Experience imperial elegance with modern amenities in one of Europe's most beautiful cities.",
        amenities: [
            'Free WiFi',
            'Restaurant',
            'Bar',
            'Concierge',
            'Laundry Service',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Classic Double',
                pricePerNight: 165,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r2',
                name: 'Imperial Suite',
                pricePerNight: 380,
                maxGuests: 2,
                bedType: 'King',
            },
        ],
    },
    {
        id: '6',
        name: 'Nordic Light Hotel',
        location: 'Stockholm, Sweden',
        country: 'SE',
        rating: 4.3,
        reviewCount: 756,
        pricePerNight: 195,
        image: 'https://loremflickr.com/1200/800/design,hotel?lock=106',
        description:
            'Scandinavian design hotel in central Stockholm. Minimalist luxury meets sustainability with locally sourced dining, sauna facilities, and stunning archipelago views.',
        amenities: [
            'Free WiFi',
            'Sauna',
            'Restaurant',
            'Bicycle Rental',
            'Fitness Center',
        ],
        rooms: [
            {
                id: 'r1',
                name: 'Nordic Single',
                pricePerNight: 145,
                maxGuests: 1,
                bedType: 'Single',
            },
            {
                id: 'r2',
                name: 'Nordic Double',
                pricePerNight: 195,
                maxGuests: 2,
                bedType: 'Double',
            },
            {
                id: 'r3',
                name: 'Nordic Suite',
                pricePerNight: 350,
                maxGuests: 2,
                bedType: 'King',
            },
        ],
    },
];

export const cars: Car[] = [
    {
        id: '1',
        make: 'Volkswagen',
        model: 'Golf',
        type: 'Compact',
        pricePerDay: 45,
        image: 'https://loremflickr.com/1200/800/volkswagen,golf?lock=201',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Petrol',
        features: [
            'GPS Navigation',
            'Bluetooth',
            'USB Charging',
            'Air Conditioning',
        ],
    },
    {
        id: '2',
        make: 'BMW',
        model: '3 Series',
        type: 'Sedan',
        pricePerDay: 85,
        image: 'https://loremflickr.com/1200/800/bmw,sedan?lock=202',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Diesel',
        features: [
            'GPS Navigation',
            'Leather Seats',
            'Heated Seats',
            'Parking Sensors',
            'Cruise Control',
        ],
    },
    {
        id: '3',
        make: 'Tesla',
        model: 'Model 3',
        type: 'Electric',
        pricePerDay: 95,
        image: 'https://loremflickr.com/1200/800/tesla,electric-car?lock=203',
        seats: 5,
        transmission: 'Automatic',
        fuelType: 'Electric',
        features: [
            'Autopilot',
            'Supercharger Access',
            'Premium Audio',
            'Glass Roof',
            'Keyless Entry',
        ],
    },
    {
        id: '4',
        make: 'Mercedes-Benz',
        model: 'V-Class',
        type: 'Van',
        pricePerDay: 120,
        image: 'https://loremflickr.com/1200/800/mercedes,van?lock=204',
        seats: 7,
        transmission: 'Automatic',
        fuelType: 'Diesel',
        features: [
            'GPS Navigation',
            'Leather Seats',
            'Climate Control',
            'Sliding Doors',
            'Large Trunk',
        ],
    },
    {
        id: '5',
        make: 'Fiat',
        model: '500',
        type: 'Economy',
        pricePerDay: 29,
        image: 'https://loremflickr.com/1200/800/fiat,city-car?lock=205',
        seats: 4,
        transmission: 'Manual',
        fuelType: 'Petrol',
        features: ['Bluetooth', 'Air Conditioning', 'USB Charging'],
    },
];

export function getHotelById(id: string): Hotel | undefined {
    return hotels.find((h) => h.id === id);
}

export function getCarById(id: string): Car | undefined {
    return cars.find((c) => c.id === id);
}
